name: Build & Publish Protege MCP Server Plugin

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g. v1.0.0)"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 9 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./ProtegeMCP.Server

    - name: Dotnet Build & Publish
      run: |
        dotnet publish -c Release -o ./publish

        ls -la ./publish
      working-directory: ./ProtegeMCP.Server

    - name: Move artifacts to java resources folder
      run: |
        mv ./publish/ProtegeMCP.Server ../ProtegeMCP.Plugin/src/main/resources/

        ls -la ../ProtegeMCP.Plugin/src/main/resources/
      working-directory: ./ProtegeMCP.Server

    - name: Set up JDK 25
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 25

    - name: Build with Maven
      run: mvn clean package --batch-mode
      working-directory: ./ProtegeMCP.Plugin

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: ProtegeMCP.Plugin
        path: ./ProtegeMCP.Plugin/target/*.jar

    - name: Create Release
      run: |
        gh release create "${{ inputs.tag }}" \
            ./ProtegeMCP.Plugin/target/*.jar \
            --title "${{ inputs.tag }}"
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload JAR to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ProtegeMCP.Plugin/target/*.jar
        asset_name: ProtegeMCP.Plugin.jar
        asset_content_type: application/java-archive
